import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { ScrollToService } from 'src/app/shared/services/scroll-to.service';
declare var $: any;
@Component({
  selector: 'app-industries',
  templateUrl: './industries.component.html',
  styleUrls: ['./industries.component.scss']
})
export class IndustriesComponent implements OnInit {
  private fragment: string;
  constructor(private route: ActivatedRoute,private scrollService: ScrollToService) { }
  //categeoryBanking:any[];
  clienteleArray:any[]=[  
    {
      id:1,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/adityabirla-money.jpg",
      imgAlt:"adityabirla-money.jpg",
      categeory:"bankingandfinance"
    },
    {
      id:2,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/anandrathi.jpg",
      imgAlt:"aanandrathi.jpg",
      categeory:"bankingandfinance"
    },
    {
      id:3,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/atoms.jpg",
      imgAlt:"atoms.jpg",
      categeory:"bankingandfinance"
    },
    {
      id:4,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/axis.png",
      imgAlt:"axis.png",
      categeory:"bankingandfinance"
    },
    {
      id:5,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/bankofbadoda.png",
      imgAlt:"bankofbadoda.png",
      categeory:"bankingandfinance"
    },
    {
      id:6,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/bhim.jpg",
      imgAlt:"bhim.jpg",
      categeory:"bankingandfinance"
    },
    {
      id:7,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/bnp-paribas.jpg",
      imgAlt:"bnp-paribas.jpg",
      categeory:"bankingandfinance"
    },
    {
      id:8,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/capital-first.png",
      imgAlt:"capital-first.png",
      categeory:"bankingandfinance"
    },
    {
      id:9,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/ccAvenue.png",
      imgAlt:"ccAvenue.png",
      categeory:"bankingandfinance"
    },
    {
      id:10,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/cms.png",
      imgAlt:"cms.png",
      categeory:"bankingandfinance"
    },
    {
      id:11,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/dena.jpg",
      imgAlt:"dena.jpg",
      categeory:"bankingandfinance"
    },
    {
      id:12,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/dspblackrocks.jpg",
      imgAlt:"dspblackrocks.jpg",
      categeory:"bankingandfinance"
    },
    {
      id:13,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/emirate.jpg",
      imgAlt:"emirate.jpg",
      categeory:"bankingandfinance"
    },
    {
      id:14,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/emurdha.jpg",
      imgAlt:"emurdha.jpg",
      categeory:"bankingandfinance"
    },
    {
      id:15,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/etransact.png",
      imgAlt:"etransact.png",
      categeory:"bankingandfinance"
    },
    {
      id:16,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/Edlewise.jpg",
      imgAlt:"Edlewise.jpg",
      categeory:"bankingandfinance"
    },
    {
      id:17,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/fastbanktransfer.png",
      imgAlt:"fastbanktransfer.png",
      categeory:"bankingandfinance"
    },
    {
      id:18,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/govbankofkuwait.png",
      imgAlt:"govbankofkuwait.png",
      categeory:"bankingandfinance"
    },
    {
      id:19,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/hdfcbank.png",
      imgAlt:"hdfcbank.png",
      categeory:"bankingandfinance"
    },
    {
      id:20,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/hsbc.png",
      imgAlt:"hsbc.png",
      categeory:"bankingandfinance"
    },
    {
      id:21,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/icici.png",
      imgAlt:"icici.png",
      categeory:"bankingandfinance"
    },
    {
      id:22,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/indiabull.jpg",
      imgAlt:"indiabull.jpg",
      categeory:"bankingandfinance"
    },
    {
      id:23,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/dena.jpg",
      imgAlt:"dena.jpg",
      categeory:"bankingandfinance"
    },
    {
      id:24,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/instarem.jpg",
      imgAlt:"instarem.jpg",
      categeory:"bankingandfinance"
    },

    {
      id:25,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/109.jpg",
      imgAlt:"109.jpg",
      categeory:"ecommerceandretail"
    },
    {
      id:26,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/compuindia.png",
      imgAlt:"compuindia.png",
      categeory:"ecommerceandretail"
    },
    {
      id:27,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/craftvilla.png",
      imgAlt:"craftvilla.png",
      categeory:"ecommerceandretail"
    },
    {
      id:26,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/decore.png",
      imgAlt:"decore.png",
      categeory:"ecommerceandretail"
    },
    {
      id:27,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/dhirubhaiAmbaniSchool.png",
      imgAlt:"dhirubhaiAmbaniSchool.png",
      categeory:"ecommerceandretail"
    },
    {
      id:28,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/ebay.jpg",
      imgAlt:"ebay.jpg",
      categeory:"ecommerceandretail"
    },
    {
      id:29,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/ederend.png",
      imgAlt:"ederend.png",
      categeory:"ecommerceandretail"
    },
    {
      id:30,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/electronics.png",
      imgAlt:"electronics.png",
      categeory:"ecommerceandretail"
    },
    {
      id:31,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/eurekaforbes.png",
      imgAlt:"eurekaforbes.png",
      categeory:"ecommerceandretail"
    },
    {
      id:32,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/ezone.png",
      imgAlt:"ezone.png",
      categeory:"ecommerceandretail"
    },
    {
      id:33,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/ganger.png",
      imgAlt:"ganger.png",
      categeory:"ecommerceandretail"
    },
    {
      id:34,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/gnc.jpg",
      imgAlt:"gnc.jpg",
      categeory:"ecommerceandretail"
    },
    {
      id:35,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/indent.jpg",
      imgAlt:"indent.jpg",
      categeory:"ecommerceandretail"
    },
    {
      id:36,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/kalki.png",
      imgAlt:"kalki.png",
      categeory:"ecommerceandretail"
    },
    {
      id:37,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/ganger.png",
      imgAlt:"ganger.png",
      categeory:"ecommerceandretail"
    },
    {
      id:38,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/localbanya.jpg",
      imgAlt:"localbanya.jpg",
      categeory:"ecommerceandretail"
    },
    {
      id:39,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/maxx.png",
      imgAlt:"maxx.png",
      categeory:"ecommerceandretail"
    },
    {
      id:40,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/naturebasket.png",
      imgAlt:"naturebasket.png",
      categeory:"ecommerceandretail"
    },
    {
      id:41,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/education&elearning/connectstd.png",
      imgAlt:"connectstd.png",
      categeory:"educationandelearning"
    },
    {
      id:42,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/education&elearning/embibe.png",
      imgAlt:"embibe.png",
      categeory:"educationandelearning"
    },
    {
      id:43,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/education&elearning/fiitjee.png",
      imgAlt:"fiitjee.png",
      categeory:"educationandelearning"
    },
    {
      id:44,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/education&elearning/futurelearning.png",
      imgAlt:"futurelearning.png",
      categeory:"educationandelearning"
    },
    {
      id:45,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/education&elearning/i-became.png",
      imgAlt:"i-became.png",
      categeory:"educationandelearning"
    },
    {
      id:46,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/education&elearning/jara-eduction.png",
      imgAlt:"jara-eduction.png",
      categeory:"educationandelearning"
    },
    {
      id:47,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/education&elearning/university-std.jpg",
      imgAlt:"university-std.jpg",
      categeory:"educationandelearning"
    },
    {
      id:48,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/education&elearning/vidyaalankar.png",
      imgAlt:"vidyaalankar.png",
      categeory:"educationandelearning"
    },
    {
      id:49,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/goverment&semigov/aircargo.png",
      imgAlt:"aircargo.png",
      categeory:"govandsemigov"
    },
    {
      id:50,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/goverment&semigov/bus.png",
      imgAlt:"bus.png",
      categeory:"govandsemigov"
    },
    {
      id:51,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/goverment&semigov/cbse.png",
      imgAlt:"cbse.png",
      categeory:"govandsemigov"
    },
    {
      id:52,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/goverment&semigov/centralexcies.png",
      imgAlt:"centralexcies.png",
      categeory:"govandsemigov"
    },
    {
      id:53,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/goverment&semigov/customeHouse.png",
      imgAlt:"customeHouse.png",
      categeory:"govandsemigov"
    },
    {
      id:54,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/goverment&semigov/dubaimetro.png",
      imgAlt:"dubaimetro.png",
      categeory:"govandsemigov"
    },
    {
      id:55,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/goverment&semigov/free.png",
      imgAlt:"free.png",
      categeory:"govandsemigov"
    },
    {
      id:56,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/goverment&semigov/hp.png",
      imgAlt:"hp.png",
      categeory:"govandsemigov"
    },
    {
      id:57,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/goverment&semigov/img.png",
      imgAlt:"img.png",
      categeory:"govandsemigov"
    },
    {
      id:58,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/goverment&semigov/maffle.png",
      imgAlt:"maffle.png",
      categeory:"govandsemigov"
    },
    {
      id:59,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/goverment&semigov/mhada.png",
      imgAlt:"mhada.png",
      categeory:"govandsemigov"
    },
    {
      id:60,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/goverment&semigov/mkcl.png",
      imgAlt:"mkcl.png",
      categeory:"govandsemigov"
    },
    {
      id:61,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/goverment&semigov/mmrc.png",
      imgAlt:"mmrc.png",
      categeory:"govandsemigov"
    },
    {
      id:62,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/goverment&semigov/nabard.png",
      imgAlt:"nabard.png",
      categeory:"govandsemigov"
    },
    {
      id:63,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/healthcare/apex.jpg",
      imgAlt:"apex.jpg",
      categeory:"healthcare"
    },
    {
      id:64,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/healthcare/barun.png",
      imgAlt:"barun.png",
      categeory:"healthcare"
    },
    {
      id:65,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/healthcare/fitternity.jpg",
      imgAlt:"fitternity.jpg",
      categeory:"healthcare"
    },
    {
      id:66,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/healthcare/hindujahospital.png",
      imgAlt:"hindujahospital.png",
      categeory:"healthcare"
    },
    {
      id:67,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/healthcare/juvederm.png",
      imgAlt:"juvederm.png",
      categeory:"healthcare"
    },
    {
      id:68,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/insurance/adityabiral-health.png",
      imgAlt:"lilawatihospital.png",
      categeory:"insurance"
    },
    {
      id:69,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/insurance/coverfox.jpg",
      imgAlt:"coverfox.jpg",
      categeory:"insurance"
    },
    {
      id:70,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/insurance/hdfcergo.png",
      imgAlt:"hdfcergo.png",
      categeory:"insurance"
    },
    {
      id:71,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/insurance/coverfox.jpg",
      imgAlt:"coverfox.jpg",
      categeory:"insurance"
    },
    {
      id:72,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/insurance/hdfcergo.png",
      imgAlt:"hdfcergo.png",
      categeory:"insurance"
    },
    {
      id:73,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/insurance/idbi-fedral.jpg",
      imgAlt:"idbi-fedral.jpg",
      categeory:"insurance"
    },
    {
      id:74,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/insurance/lic.png",
      imgAlt:"lic.png",
      categeory:"insurance"
    },
    {
      id:75,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/insurance/rel-genral-insurance.png",
      imgAlt:"rel-genral-insurance.png",
      categeory:"insurance"
    },
    {
      id:76,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/insurance/rel-life.png",
      imgAlt:"rel-life.png",
      categeory:"insurance"
    },
    {
      id:78,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/insurance/tata-aia.jpg",
      imgAlt:"tata-aia.jpg",
      categeory:"insurance"
    },
    {
      id:79,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/accelya.png",
      imgAlt:"accelya.png",
      categeory:"itandconsulting"
    },
    {
      id:80,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/aurionpro.jpg",
      imgAlt:"aurionpro.jpg",
      categeory:"itandconsulting"
    },
    {
      id:81,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/b2x.jpg",
      imgAlt:"b2x.jpg",
      categeory:"itandconsulting"
    },
    {
      id:82,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/bcg.png",
      imgAlt:"bcg.png",
      categeory:"itandconsulting"
    },
    {
      id:83,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/bristcone.jpg",
      imgAlt:"bristcone.jpg",
      categeory:"itandconsulting"
    },
    {
      id:84,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/cnergyis.png",
      imgAlt:"cnergyis.png",
      categeory:"itandconsulting"
    },
    {
      id:85,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/creatwelland.jpg",
      imgAlt:"creatwelland.jpg",
      categeory:"itandconsulting"
    },
    {
      id:86,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/datamatic.png",
      imgAlt:"datamatic.png",
      categeory:"itandconsulting"
    },
    {
      id:87,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/dlink.jpg",
      imgAlt:"dlink.jpg",
      categeory:"itandconsulting"
    },
    {
      id:88,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/ey.png",
      imgAlt:"ey.png",
      categeory:"itandconsulting"
    },
    {
      id:89,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/ezest.jpg",
      imgAlt:"ezest.jpg",
      categeory:"itandconsulting"
    },
    {
      id:90,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/fountainhead.jpg",
      imgAlt:"fountainhead.jpg",
      categeory:"itandconsulting"
    },
    {
      id:91,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/gep.png",
      imgAlt:"gep.png",
      categeory:"itandconsulting"
    },
    {
      id:92,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/goldmine.jpg",
      imgAlt:"goldmine.jpg",
      categeory:"itandconsulting"
    },
    {
      id:93,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/iglilck.jpg",
      imgAlt:"iglilck.jpg",
      categeory:"itandconsulting"
    },
    {
      id:94,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/infratech.png",
      imgAlt:"infratech.png",
      categeory:"itandconsulting"
    },
    {
      id:95,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/inoram.png",
      imgAlt:"inoram.png",
      categeory:"itandconsulting"
    },
    {
      id:96,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/intelnet.jpg",
      imgAlt:"intelnet.jpg",
      categeory:"itandconsulting"
    },
    {
      id:97,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/iris.png",
      imgAlt:"iris.png",
      categeory:"itandconsulting"
    },
    {
      id:98,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/kmmg.png",
      imgAlt:"kmmg.png",
      categeory:"itandconsulting"
    },
    {
      id:99,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/mastek.jpg",
      imgAlt:"mastek.jpg",
      categeory:"itandconsulting"
    },
    {
      id:100,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/mindtree.jpg",
      imgAlt:"mindtree.jpg",
      categeory:"itandconsulting"
    },
    {
      id:101,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/mk.png",
      imgAlt:"mk.png",
      categeory:"itandconsulting"
    },
    {
      id:102,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/netcore.jpg",
      imgAlt:"netcore.jpg",
      categeory:"itandconsulting"
    },
    {
      id:103,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/manufacturing/109f.jpg",
      imgAlt:"109",
      categeory:"manufacturing"
    },
    {
      id:104,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/manufacturing/acc.png",
      imgAlt:"acc",
      categeory:"manufacturing"
    },
    {
      id:105,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/manufacturing/bacardi.png",
      imgAlt:"bacardi.png",
      categeory:"manufacturing"
    },
    {
      id:106,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/manufacturing/baidinath.jpg",
      imgAlt:"baidinath.jpg",
      categeory:"manufacturing"
    },
    {
      id:107,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/manufacturing/bajaj.jpg",
      imgAlt:"bajaj",
      categeory:"manufacturing"
    },
    {
      id:108,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/manufacturing/bapco.png",
      imgAlt:"bapco.png",
      categeory:"manufacturing"
    },
    {
      id:109,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/manufacturing/bayer.png",
      imgAlt:"bayer.png",
      categeory:"manufacturing"
    },
    {
      id:110,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/manufacturing/bharatbenz.png",
      imgAlt:"bharatbenz.png",
      categeory:"manufacturing"
    },
    {
      id:111,
      imgUrl:"../../../..//assets/images/whowearemodule/clientele/media&entertainment/adfactors.png",
      imgAlt:"adfactor",
      categeory:"media"
    },
    {
      id:112,
      imgUrl:"../../../..//assets/images/whowearemodule/clientele/media&entertainment/bpigram.png",
      imgAlt:"bpigram.png",
      categeory:"media"
    },
    {
      id:113,
      imgUrl:"../../../..//assets/images/whowearemodule/clientele/media&entertainment/eros.jpg",
      imgAlt:"eros.jpg",
      categeory:"media"
    },
    {
      id:114,
      imgUrl:"../../../..//assets/images/whowearemodule/clientele/media&entertainment/hungama.png",
      imgAlt:"hungama.png",
      categeory:"media"
    },
    {
      id:115,
      imgUrl:"../../../..//assets/images/whowearemodule/clientele/media&entertainment/ndtv.jpg",
      imgAlt:"ndtv.jpg",
      categeory:"media"
    },
    {
      id:116,
      imgUrl:"../../../..//assets/images/whowearemodule/clientele/media&entertainment/olx.jpg",
      imgAlt:"olx.jpg",
      categeory:"media"
    },
    {
      id:117,
      imgUrl:"../../../..//assets/images/whowearemodule/clientele/media&entertainment/rajshrifoundation.png",
      imgAlt:"rajshrifoundation.png",
      categeory:"media"
    },
    {
      id:118,
      imgUrl:"../../../..//assets/images/whowearemodule/clientele/media&entertainment/redfm.png",
      imgAlt:"redfm.png",
      categeory:"media"
    },
    {
      id:119,
      imgUrl:"../../../..//assets/images/whowearemodule/clientele/media&entertainment/rel-broadcast.png",
      imgAlt:"rel-broadcast.png",
      categeory:"media"
    },
    {
      id:120,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/new&publication/businessstandard.png",
      imgAlt:"rel-broadcast.png",
      categeory:"news"
    },
    {
      id:121,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/new&publication/condevast.png",
      imgAlt:"condevast.png",
      categeory:"news"
    },
    {
      id:122,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/new&publication/cpimedia.png",
      imgAlt:"cpimedia.png",
      categeory:"news"
    },
    {
      id:123,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/new&publication/essar.png",
      imgAlt:"essar.png",
      categeory:"news"
    },
    {
      id:124,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/new&publication/food.jpg",
      imgAlt:"food.jpg",
      categeory:"news"
    },
    {
      id:125,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/new&publication/gq.png",
      imgAlt:"gq.png",
      categeory:"news"
    },
    {
      id:126,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/new&publication/harperColics.png",
      imgAlt:"harperColics.png",
      categeory:"news"
    },
    {
      id:127,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/new&publication/jayMaharashtra.png",
      imgAlt:"jayMaharashtra.png",
      categeory:"news"
    },
    {
      id:128,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/new&publication/loksatta.png",
      imgAlt:"loksatta.png",
      categeory:"news"
    },
    {
      id:129,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/new&publication/republic.jpg",
      imgAlt:"republic.jpg",
      categeory:"news"
    },
    {
      id:130,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/startup/109start.jpg",
      imgAlt:"republic.jpg",
      categeory:"startups"
    },
    {
      id:131,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/startup/20dressess.png",
      imgAlt:"20dressess.png",
      categeory:"startups"
    },
    {
      id:132,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/startup/birdazhi.png",
      imgAlt:"birdazhi.png",
      categeory:"startups"
    },
    {
      id:133,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/startup/bombayShirCompany.png",
      imgAlt:"bombayShirCompany.png",
      categeory:"startups"
    },
    {
      id:134,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/startup/electronix.png",
      imgAlt:"electronix.png",
      categeory:"startups"
    },
    {
      id:135,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/startup/fitnessforce.jpg",
      imgAlt:"fitnessforce.jpg",
      categeory:"startups"
    },
    {
      id:136,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/startup/fitternity.jpg",
      imgAlt:"fitternity.jpg",
      categeory:"startups"
    },
    {
      id:137,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/startup/fluwithfarecon.png",
      imgAlt:"fluwithfarecon.png",
      categeory:"startups"
    },
    {
      id:138,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/telecom/blackberrry.png",
      imgAlt:"blackberrry",
      categeory:"telecom"
    },
    {
      id:139,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/telecom/virgin.png",
      imgAlt:"virgin.png",
      categeory:"telecom"
    },
    {
      id:140,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/telecom/tmobile.png",
      imgAlt:"tmobile.png",
      categeory:"telecom"
    },
    {
      id:141,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/telecom/tatacommunication.png",
      imgAlt:"tatacommunication.png",
      categeory:"telecom"
    },
    {
      id:142,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/telecom/stc.png",
      imgAlt:"stc.png",
      categeory:"telecom"
    },
    {
      id:143,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/telecom/red.png",
      imgAlt:"red.png",
      categeory:"telecom"
    },
    {
      id:144,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/telecom/play.jpg",
      imgAlt:"play.jpg",
      categeory:"telecom"
    },
    {
      id:145,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/telecom/mxl.png",
      imgAlt:"mxl.png",
      categeory:"telecom"
    },
    {
      id:146,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/telecom/mtn.png",
      imgAlt:"mtn.png",
      categeory:"telecom"
    },
    {
      id:147,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/telecom/blackberrry.png",
      imgAlt:"blackberrry",
      categeory:"telecom"
    },
    {
      id:148,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/telecom/etislat.jpg",
      imgAlt:"etislat.jpg",
      categeory:"telecom"
    },
    {
      id:149,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/healthcare/lilawatihospital.png",
      imgAlt:"lilawatihospital.png",
      categeory:"healthcare"
    },
  ]

   categeoryBanking= this.clienteleArray.filter( (arrayElement)=>{ return arrayElement.categeory == "bankingandfinance"});
   categeoryEcommerce= this.clienteleArray.filter( (arrayElement)=>{ return arrayElement.categeory == "ecommerceandretail"});
   categeoryEducation= this.clienteleArray.filter( (arrayElement)=>{ return arrayElement.categeory == "educationandelearning"});
   categeoryGovandSemigov= this.clienteleArray.filter( (arrayElement)=>{ return arrayElement.categeory == "govandsemigov"});
   categeoryHealthcare= this.clienteleArray.filter( (arrayElement)=>{ return arrayElement.categeory == "healthcare"});
   categeoryInsurance= this.clienteleArray.filter( (arrayElement)=>{ return arrayElement.categeory == "insurance"});
   categeoryItandConsulting= this.clienteleArray.filter( (arrayElement)=>{ return arrayElement.categeory == "itandconsulting"});
   categeoryManufacturing = this.clienteleArray.filter( (arrayElement) => { return arrayElement.categeory == "manufacturing"});
   categeoryMedia = this.clienteleArray.filter((arrayElement) => { return arrayElement.categeory == "media"});
   categeoryNews = this.clienteleArray.filter( (arrayElement) => { return arrayElement.categeory == "news"})
   categeoryStartups = this.clienteleArray.filter((arrayElement) => { return arrayElement.categeory == "startups"});
   categeoryTelecom = this.clienteleArray.filter( (arrayElement) => { return arrayElement.categeory == "telecom"});


  goToLink(url: string){
    window.open(url, "_blank");
  }
  ngOnInit() {
    // console.log(categeoryBanking);
    this.route.fragment.subscribe(fragment => { this.fragment = fragment; });
    console.log(this.fragment);
    // this.scrollService.triggerScrollTo(this.fragment);
    
  }

}
