import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-clientele-list',
  templateUrl: './clientele-list.component.html',
  styleUrls: ['./clientele-list.component.scss']
})
export class ClienteleListComponent implements OnInit {

  constructor() { }

  clienteleArray:any[]=[
    {
      id:1,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/adityabirla-money.jpg",
      imgAlt:"adityabirla-money.jpg",
      categeory:"bankingandfinance"
    },
    {
      id:2,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/anandrathi.jpg",
      imgAlt:"aanandrathi.jpg",
      categeory:"bankingandfinance"
    },
    {
      id:3,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/atoms.jpg",
      imgAlt:"atoms.jpg",
      categeory:"bankingandfinance"
    },
    {
      id:4,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/axis.png",
      imgAlt:"axis.png",
      categeory:"bankingandfinance"
    },
    {
      id:5,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/bankofbadoda.png",
      imgAlt:"bankofbadoda.png",
      categeory:"bankingandfinance"
    },
    {
      id:6,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/bhim.jpg",
      imgAlt:"bhim.jpg",
      categeory:"bankingandfinance"
    },
    {
      id:7,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/bnp-paribas.jpg",
      imgAlt:"bnp-paribas.jpg",
      categeory:"bankingandfinance"
    },
    {
      id:8,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/capital-first.png",
      imgAlt:"capital-first.png",
      categeory:"bankingandfinance"
    },
    {
      id:9,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/ccAvenue.png",
      imgAlt:"ccAvenue.png",
      categeory:"bankingandfinance"
    },
    {
      id:10,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/cms.png",
      imgAlt:"cms.png",
      categeory:"bankingandfinance"
    },
    {
      id:11,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/dena.jpg",
      imgAlt:"dena.jpg",
      categeory:"bankingandfinance"
    },
    {
      id:12,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/dspblackrocks.jpg",
      imgAlt:"dspblackrocks.jpg",
      categeory:"bankingandfinance"
    },
    {
      id:13,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/emirate.jpg",
      imgAlt:"emirate.jpg",
      categeory:"bankingandfinance"
    },
    {
      id:14,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/emurdha.jpg",
      imgAlt:"emurdha.jpg",
      categeory:"bankingandfinance"
    },
    {
      id:15,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/etransact.png",
      imgAlt:"etransact.png",
      categeory:"bankingandfinance"
    },
    {
      id:16,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/Edlewise.jpg",
      imgAlt:"Edlewise.jpg",
      categeory:"bankingandfinance"
    },
    {
      id:17,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/fastbanktransfer.png",
      imgAlt:"fastbanktransfer.png",
      categeory:"bankingandfinance"
    },
    {
      id:18,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/govbankofkuwait.png",
      imgAlt:"govbankofkuwait.png",
      categeory:"bankingandfinance"
    },
    {
      id:19,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/hdfcbank.png",
      imgAlt:"hdfcbank.png",
      categeory:"bankingandfinance"
    },
    {
      id:20,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/hsbc.png",
      imgAlt:"hsbc.png",
      categeory:"bankingandfinance"
    },
    {
      id:21,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/icici.png",
      imgAlt:"icici.png",
      categeory:"bankingandfinance"
    },
    {
      id:22,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/indiabull.jpg",
      imgAlt:"indiabull.jpg",
      categeory:"bankingandfinance"
    },
    {
      id:23,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/dena.jpg",
      imgAlt:"dena.jpg",
      categeory:"bankingandfinance"
    },
    {
      id:24,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/bankingandfinance/instarem.jpg",
      imgAlt:"instarem.jpg",
      categeory:"bankingandfinance"
    },

    {
      id:25,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/109.jpg",
      imgAlt:"109.jpg",
      categeory:"ecommerceandretail"
    },
    {
      id:26,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/compuindia.png",
      imgAlt:"compuindia.png",
      categeory:"ecommerceandretail"
    },
    {
      id:27,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/craftvilla.png",
      imgAlt:"craftvilla.png",
      categeory:"ecommerceandretail"
    },
    {
      id:26,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/decore.png",
      imgAlt:"decore.png",
      categeory:"ecommerceandretail"
    },
    {
      id:27,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/dhirubhaiAmbaniSchool.png",
      imgAlt:"dhirubhaiAmbaniSchool.png",
      categeory:"ecommerceandretail"
    },
    {
      id:28,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/ebay.jpg",
      imgAlt:"ebay.jpg",
      categeory:"ecommerceandretail"
    },
    {
      id:29,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/ederend.png",
      imgAlt:"ederend.png",
      categeory:"ecommerceandretail"
    },
    {
      id:30,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/electronics.png",
      imgAlt:"electronics.png",
      categeory:"ecommerceandretail"
    },
    {
      id:31,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/eurekaforbes.png",
      imgAlt:"eurekaforbes.png",
      categeory:"ecommerceandretail"
    },
    {
      id:32,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/ezone.png",
      imgAlt:"ezone.png",
      categeory:"ecommerceandretail"
    },
    {
      id:33,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/ganger.png",
      imgAlt:"ganger.png",
      categeory:"ecommerceandretail"
    },
    {
      id:34,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/gnc.jpg",
      imgAlt:"gnc.jpg",
      categeory:"ecommerceandretail"
    },
    {
      id:35,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/indent.jpg",
      imgAlt:"indent.jpg",
      categeory:"ecommerceandretail"
    },
    {
      id:36,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/kalki.png",
      imgAlt:"kalki.png",
      categeory:"ecommerceandretail"
    },
    {
      id:37,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/ganger.png",
      imgAlt:"ganger.png",
      categeory:"ecommerceandretail"
    },
    {
      id:38,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/localbanya.jpg",
      imgAlt:"localbanya.jpg",
      categeory:"ecommerceandretail"
    },
    {
      id:39,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/maxx.png",
      imgAlt:"maxx.png",
      categeory:"ecommerceandretail"
    },
    {
      id:40,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/ecommerce&retail/naturebasket.png",
      imgAlt:"naturebasket.png",
      categeory:"ecommerceandretail"
    },
    {
      id:41,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/education&elearning/connectstd.png",
      imgAlt:"connectstd.png",
      categeory:"educationandelearning"
    },
    {
      id:42,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/education&elearning/embibe.png",
      imgAlt:"embibe.png",
      categeory:"educationandelearning"
    },
    {
      id:43,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/education&elearning/fiitjee.png",
      imgAlt:"fiitjee.png",
      categeory:"educationandelearning"
    },
    {
      id:44,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/education&elearning/futurelearning.png",
      imgAlt:"futurelearning.png",
      categeory:"educationandelearning"
    },
    {
      id:45,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/education&elearning/i-became.png",
      imgAlt:"i-became.png",
      categeory:"educationandelearning"
    },
    {
      id:46,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/education&elearning/jara-eduction.png",
      imgAlt:"jara-eduction.png",
      categeory:"educationandelearning"
    },
    {
      id:47,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/education&elearning/university-std.jpg",
      imgAlt:"university-std.jpg",
      categeory:"educationandelearning"
    },
    {
      id:48,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/education&elearning/vidyaalankar.png",
      imgAlt:"vidyaalankar.png",
      categeory:"educationandelearning"
    },
    {
      id:49,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/goverment&semigov/aircargo.png",
      imgAlt:"aircargo.png",
      categeory:"govandsemigov"
    },
    {
      id:50,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/goverment&semigov/bus.png",
      imgAlt:"bus.png",
      categeory:"govandsemigov"
    },
    {
      id:51,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/goverment&semigov/cbse.png",
      imgAlt:"cbse.png",
      categeory:"govandsemigov"
    },
    {
      id:52,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/goverment&semigov/centralexcies.png",
      imgAlt:"centralexcies.png",
      categeory:"govandsemigov"
    },
    {
      id:53,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/goverment&semigov/customeHouse.png",
      imgAlt:"customeHouse.png",
      categeory:"govandsemigov"
    },
    {
      id:54,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/goverment&semigov/dubaimetro.png",
      imgAlt:"dubaimetro.png",
      categeory:"govandsemigov"
    },
    {
      id:55,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/goverment&semigov/free.png",
      imgAlt:"free.png",
      categeory:"govandsemigov"
    },
    {
      id:56,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/goverment&semigov/hp.png",
      imgAlt:"hp.png",
      categeory:"govandsemigov"
    },
    {
      id:57,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/goverment&semigov/img.png",
      imgAlt:"img.png",
      categeory:"govandsemigov"
    },
    {
      id:58,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/goverment&semigov/maffle.png",
      imgAlt:"maffle.png",
      categeory:"govandsemigov"
    },
    {
      id:59,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/goverment&semigov/mhada.png",
      imgAlt:"mhada.png",
      categeory:"govandsemigov"
    },
    {
      id:60,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/goverment&semigov/mkcl.png",
      imgAlt:"mkcl.png",
      categeory:"govandsemigov"
    },
    {
      id:61,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/goverment&semigov/mmrc.png",
      imgAlt:"mmrc.png",
      categeory:"govandsemigov"
    },
    {
      id:62,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/goverment&semigov/nabard.png",
      imgAlt:"nabard.png",
      categeory:"govandsemigov"
    },
    {
      id:63,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/healthcare/apex.jpg",
      imgAlt:"apex.jpg",
      categeory:"healthcare"
    },
    {
      id:64,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/healthcare/barun.png",
      imgAlt:"barun.png",
      categeory:"healthcare"
    },
    {
      id:65,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/healthcare/fitternity.jpg",
      imgAlt:"fitternity.jpg",
      categeory:"healthcare"
    },
    {
      id:66,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/healthcare/hindujahospital.png",
      imgAlt:"hindujahospital.png",
      categeory:"healthcare"
    },
    {
      id:67,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/healthcare/juvederm.png",
      imgAlt:"juvederm.png",
      categeory:"healthcare"
    },
    {
      id:68,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/insurance/adityabiral-health.png",
      imgAlt:"lilawatihospital.png",
      categeory:"insurance"
    },
    {
      id:69,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/insurance/coverfox.jpg",
      imgAlt:"coverfox.jpg",
      categeory:"insurance"
    },
    {
      id:70,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/insurance/hdfcergo.png",
      imgAlt:"hdfcergo.png",
      categeory:"insurance"
    },
    {
      id:71,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/insurance/coverfox.jpg",
      imgAlt:"coverfox.jpg",
      categeory:"insurance"
    },
    {
      id:72,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/insurance/hdfcergo.png",
      imgAlt:"hdfcergo.png",
      categeory:"insurance"
    },
    {
      id:73,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/insurance/idbi-fedral.jpg",
      imgAlt:"idbi-fedral.jpg",
      categeory:"insurance"
    },
    {
      id:74,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/insurance/lic.png",
      imgAlt:"lic.png",
      categeory:"insurance"
    },
    {
      id:75,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/insurance/rel-genral-insurance.png",
      imgAlt:"rel-genral-insurance.png",
      categeory:"insurance"
    },
    {
      id:76,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/insurance/rel-life.png",
      imgAlt:"rel-life.png",
      categeory:"insurance"
    },
    {
      id:78,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/insurance/tata-aia.jpg",
      imgAlt:"tata-aia.jpg",
      categeory:"insurance"
    },
    {
      id:79,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/accelya.png",
      imgAlt:"accelya.png",
      categeory:"itandconsulting"
    },
    {
      id:80,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/aurionpro.jpg",
      imgAlt:"aurionpro.jpg",
      categeory:"itandconsulting"
    },
    {
      id:81,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/b2x.jpg",
      imgAlt:"b2x.jpg",
      categeory:"itandconsulting"
    },
    {
      id:82,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/bcg.png",
      imgAlt:"bcg.png",
      categeory:"itandconsulting"
    },
    {
      id:83,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/bristcone.jpg",
      imgAlt:"bristcone.jpg",
      categeory:"itandconsulting"
    },
    {
      id:84,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/cnergyis.png",
      imgAlt:"cnergyis.png",
      categeory:"itandconsulting"
    },
    {
      id:85,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/creatwelland.jpg",
      imgAlt:"creatwelland.jpg",
      categeory:"itandconsulting"
    },
    {
      id:86,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/datamatic.png",
      imgAlt:"datamatic.png",
      categeory:"itandconsulting"
    },
    {
      id:87,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/dlink.jpg",
      imgAlt:"dlink.jpg",
      categeory:"itandconsulting"
    },
    {
      id:88,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/ey.png",
      imgAlt:"ey.png",
      categeory:"itandconsulting"
    },
    {
      id:89,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/ezest.jpg",
      imgAlt:"ezest.jpg",
      categeory:"itandconsulting"
    },
    {
      id:90,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/fountainhead.jpg",
      imgAlt:"fountainhead.jpg",
      categeory:"itandconsulting"
    },
    {
      id:91,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/gep.png",
      imgAlt:"gep.png",
      categeory:"itandconsulting"
    },
    {
      id:92,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/goldmine.jpg",
      imgAlt:"goldmine.jpg",
      categeory:"itandconsulting"
    },
    {
      id:93,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/iglilck.jpg",
      imgAlt:"iglilck.jpg",
      categeory:"itandconsulting"
    },
    {
      id:94,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/infratech.png",
      imgAlt:"infratech.png",
      categeory:"itandconsulting"
    },
    {
      id:95,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/inoram.png",
      imgAlt:"inoram.png",
      categeory:"itandconsulting"
    },
    {
      id:96,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/intelnet.jpg",
      imgAlt:"intelnet.jpg",
      categeory:"itandconsulting"
    },
    {
      id:97,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/iris.png",
      imgAlt:"iris.png",
      categeory:"itandconsulting"
    },
    {
      id:98,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/kmmg.png",
      imgAlt:"kmmg.png",
      categeory:"itandconsulting"
    },
    {
      id:99,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/mastek.jpg",
      imgAlt:"mastek.jpg",
      categeory:"itandconsulting"
    },
    {
      id:100,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/mindtree.jpg",
      imgAlt:"mindtree.jpg",
      categeory:"itandconsulting"
    },
    {
      id:101,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/mk.png",
      imgAlt:"mk.png",
      categeory:"itandconsulting"
    },
    {
      id:102,
      imgUrl:"../../../../assets/images/whowearemodule/clientele/it&consulting/netcore.jpg",
      imgAlt:"netcore.jpg",
      categeory:"itandconsulting"
    }
  ]

  ngOnInit() {
  }

}
